app/apps/api/userprofile/urls.py
from django.urls import path, include
from .views import UserProfileRetriveAPIView
from .views import UserFollowersListAPIView, UserFollowingListAPIView


urlpatterns = [
	# Endpoint for retrieving the user's own profile information.
	path('profile/', UserProfileRetriveAPIView.as_view({'get': 'retrieve', 'patch': 'partial_update'})),

	# Includes URLs from the 'api.content.urls', likely for managing and viewing user posts.
	path('postfeed/', include('api.content.urls')),

	# Includes URLs from the 'api.userpost.urls', presumably for managing and viewing user-specific posts.
	path('posts/', include('api.userpost.urls')),

	# Includes URLs from the 'api.notification.urls', possibly for managing and viewing user notifications.
	path('notification/', include('api.notification.urls')),

	# Endpoint for retrieving the list of followers for the user.
	path('followers/', UserFollowersListAPIView.as_view()),

	# Endpoint for retrieving the list of users whom the user is following.
	path('following/', UserFollowingListAPIView.as_view()),
]

app/apps/tools/urls.py
from django.urls import path
from .views import *

app_name = 'tools'

urlpatterns = [
	path('like/', post_like, name='post_like'),
	path('comment/', post_comment, name='post_comment'),
	path('follow/', follow_profile, name='follow_profile'),
	path('upload_photo/', upload_photo, name='upload_photo'),
	path('upload_avatar/', upload_avatar, name='upload_avatar'),
	path('delete_photo/', delete_photo, name='delete_photo')
]

app/apps/userpost/urls.py
from django.urls import path
from .views import PhotoView

app_name = 'userpost'

urlpatterns = [
	path('', PhotoView.as_view(), name='userpost')
]

app/apps/userprofile/urls.py
from django.urls import path
from .views import ProfileView, FollowersView, UserLogoutView

app_name = 'userprofile'

urlpatterns = [
	path('logout/', UserLogoutView.as_view(), name='logout'),
	path('followers/', FollowersView.as_view(), name='followers'),
	path('following/', FollowersView.as_view(), name='following'),
	path('', ProfileView.as_view(), name='userprofile'),
]	

app/instclone/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
	path('', include('main.urls')),
	path('content/', include('content.urls')),
	path('admin/', admin.site.urls),
	path('notifications/', include('notifications.urls')),
    path('explore/', include('explore.urls')),
	path('p/<int:pk>/', include('userpost.urls')),
    path('tools/', include('tools.urls')),
    path('api/v1/', include('api.urls')),
	path('<str:username>/', include('userprofile.urls')),
]

if settings.DEBUG:
    import debug_toolbar	

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/apps/userprofile/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from decouple import config
from django.urls import reverse
from storages.backends.s3boto3 import S3Boto3Storage
import uuid

class AvatarS3Storage(S3Boto3Storage):
	"""
	Class for storing avatar image files in Amazon S3 storage.

	"""
	# Define the location where avatar files will be stored in S3.
	location = 'avatar'

	def generate_unique_filename(self):
		"""
		Generate a unique file name using the uuid module.

		"""
		return f'{uuid.uuid4()}.jpg'

	def save(self, name, content, max_length=None, **kwargs):
		"""
		Override the save method to generate a unique file name before saving.

		Returns:
			str: File name after saving.
		"""

		# Generate a unique file name.
		name = self.generate_unique_filename()

		# Call the parent save method with the unique file name.
		return super().save(name, content, max_length, **kwargs)


class User(AbstractUser):
	"""
	Custom user model extending the AbstractUser.

	Attributes:
		bio (TextField): Text field for user biography, allowing up to 500 characters.
		avatar (ImageField): Image field for user avatar.
		follow (ManyToManyField): Many-to-many relationship for user following other users.
	"""

	bio = models.TextField(
		max_length=500, 
		blank=True)
	avatar = models.ImageField(
		storage=AvatarS3Storage(),
		blank=True)
	follow = models.ManyToManyField(
		'self', 
		related_name='following', 
		symmetrical=False, 
		blank=True)

	def get_url(self):
		"""
		Get the URL of the user's avatar.

		Returns:
			str: URL of the user's avatar.
		"""
		internal_url = self.avatar.url
		return internal_url.replace(config('AWS_S3_ENDPOINT_URL'),
									config('AWS_S3_ENDPOINT'))

	def get_absolute_url(self):
		"""
		Get the absolute URL of the user's profile.

		Returns:
			str: Absolute URL of the user's profile.
		"""
		return reverse('photo_detail', kwargs={'pk': self.pk})

app/apps/api/userprofile/views.py
from rest_framework.generics import RetrieveAPIView, ListAPIView
from rest_framework.viewsets import ModelViewSet, GenericViewSet
from userprofile.models import User
from .serializers import UserProfileSerializer, UserListSerializator
from django.db.models import Count, Prefetch
from rest_framework import mixins
from api.userpost.permissions import ProfilePermission



class UserProfileRetriveAPIView(mixins.RetrieveModelMixin,
								mixins.UpdateModelMixin,
								GenericViewSet):
	"""
	View class for retrieving the profile information of a specific user.

	Uses UserProfileSerializer to serialize the user's profile information.
	Overrides get_object to customize the queryset and annotate additional 
	information such as follower count, following count, and post count.

	"""
	permission_classes = [ProfilePermission]
	serializer_class = UserProfileSerializer

	def get_object(self):
		username = self.kwargs.get('username')

		# Querying the user's profile and annotating follower count, following count, and post count.
		profile = User.objects.filter(username=username).annotate(
			follow_count=Count('following', distinct=True),
			following_count=Count('follow', distinct=True),
			post_count=Count('post', distinct=True)
		).only('username', 'avatar', 'bio').first()

		return profile


class UserFollowersListAPIView(ListAPIView):
	"""
	View class for retrieving the list of followers for a specific user.

	Uses UserListSerializator to serialize the list of followers.

	"""

	serializer_class = UserListSerializator

	def get_queryset(self):
		username = self.kwargs.get('username')

		# Querying users who follow the specified user.
		followers = User.objects.only('follow').filter(username=username)

		# Extracting usernames of followers.
		follower_usernames = followers.values_list('follow__username', flat=True)

		# Querying profiles of followers based on usernames.
		follower_profiles = User.objects.filter(
			username__in=follower_usernames).only('username', 'avatar')

		return follower_profiles


class UserFollowingListAPIView(ListAPIView):
	"""
	View class for retrieving the list of users whom a specific user is following.

	Uses UserListSerializator to serialize the list of users being followed.

	"""

	serializer_class = UserListSerializator

	def get_queryset(self):
		username = self.kwargs.get('username')

		# Querying users whom the specified user is following.
		following = User.objects.only('following').filter(username=username)

		# Extracting usernames of users being followed.
		following_usernames = following.values_list('following__username', flat=True)

		# Querying profiles of users being followed based on usernames.
		following_profiles = User.objects.filter(
			username__in=following_usernames).only('username', 'avatar')

		return following_profiles

app/apps/userprofile/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import User
from .userprofile_services import extended_information, get_filtered_photos, get_filtered_profiles
from django.contrib.auth.views import LogoutView

class ProfileView(ListView):
	"""
	View for displaying user profile and associated photos.

	"""

	context_object_name = 'photos'
	template_name = 'userprofile/profile.html'

	def get_queryset(self):
		"""
		Get the queryset of photos for the current user.

		Returns:
			QuerySet: Filtered queryset containing photos for the current user.
		"""
		return get_filtered_photos(self)
	
	def get_context_data(self, **kwargs):
		"""
		Get additional context data for the profile view.

		Returns:
			dict: Updated context data with extended information.
		"""
		context = super().get_context_data(**kwargs)
		return extended_information(self, context, **kwargs)

class FollowersView(ListView):
	"""
	View for displaying followers of a user.

	"""

	model = User
	template_name = 'userprofile/followers_view.html'
	context_object_name = 'followers'

	def get_queryset(self):
		"""
		Get the queryset of followers for the current user.

		Returns:
			QuerySet: Filtered queryset containing followers for the current user.
		"""
		return get_filtered_profiles(self)

class UserLogoutView(LogoutView):
	"""
	View for logging out a user.

	"""
	
	next_page = '/'

app/apps/userprofile/templates/userprofile/followers_view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="followers-content">
	<ul class="followers-list">
		{% for follower in followers %}
			<li class="follower-card">
				<a href="{% url 'userprofile:userprofile' follower.username %}">
					<img class="followers-photo" src="{% static 'main/images/default.jpg' %}" alt="" width="70">
					<div class="follower-name">{{ follower.username }}</div>
				</a>
			</li>
		{% endfor %}
	</ul>
</div>
{% endblock %}

app/apps/userprofile/templates/userprofile/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{% endblock %}
{% block content %}
<div class="section">
<div class="profile-section">
	<div class="profile-image">
	{% if profile.avatar %}
	{% csrf_token %}
		<img src="{{ profile.get_url }}" alt="">
		<input type="file" id="avatarUpload" style="display: none;">
		<i class="fa-solid fa-circle-plus upload_btn" style="display: none;"></i>
	{% else %}
	{% csrf_token %}
		<img src="{% static 'main/images/default.jpg' %}" alt="">
		<input type="file" id="avatarUpload" style="display: none;">
		<i class="fa-solid fa-circle-plus upload_btn" style="display: none;"></i>
	{% endif %}
	</div>
	<div class="profile-menu">
		<div class="profile-user-settings">
			<div class="profile-user-name">{{ profile.username }}</div>
			{% if profile_owner %}
				<form action="" method="post">
					{% csrf_token %}
					<button type="submit" class="profile-btn" id="editProfileButton">Change profile</button>
				</form>
			{% else %}
				<form action="{% url 'tools:follow_profile' %}" method="post">
					{% csrf_token %}
					{% if is_following %}
					<input type="hidden" name="username" value="{{ profile.username }}">
					<input type="hidden" name="follow" value="unfollow">
					<button type="submit" value="unfollow" name="follow" class="profile-btn">
						Unfollow
					</button>
					{% else %}
					<input type="hidden" name="username" value="{{ profile.username }}">
					<input type="hidden" name="follow" value="follow">
					<button type="submit" value="follow" name="follow" class="profile-btn">
						Follow
					</button>
					{% endif %}
				</form>
			{% endif %}
			<button aria-label="profile settings" class="btn profile-settings-btn">
				{% if profile_owner %}
				<div class="icon-container">
					<div class="hover-area">
						<i class="fa-solid fa-gear"></i>
						<a href="{% url 'userprofile:logout' request.user.username %}" class="text-link">LogOut</a>
					</div>
				</div>
				{% else %}
					<i class="fa-solid fa-bars"></i>
				{% endif %}
			</button>
			
			
		</div>
		<div class="profile-stats">
			<ul>
				<li><span class="profile-stat-count"></span>{{ post_count }} posts</li>
				<li><span class="profile-stat-count"></span><a href="{% url 'userprofile:followers' profile.username %}">{{ profile.follow_count }} followers</a></li>
				<li><span class="profile-stat-count"></span><a href="{% url 'userprofile:following' profile.username %}">{{ profile.following_count }} following</a></li>
			</ul>
		</div>
		<div class="profile-bio">

			<p>
				<span class="profile-real-name">
					{{ profile.bio }}
				</span>
				
			</p>
		</div>
	</div>
</div>
<!-- end profile-section -->
<div class="gallary-section">
	{%for photo in photos %}
		<div class="gallary">
			<div class="photo" data-id="{{photo.id}}">
				<a href="{% url 'userpost:userpost' photo.pk %}">
					<div class="gallary-item" tabindex="0">
						<img class="gallary-image photo" src="{{ photo.get_url }}" alt="">
					</div>
				</a>
				<button class="deleteButton" style="display: none;">X</button>
			</div>			
			
		</div>
		{% endfor %}
</div>
</div>


{% endblock %}