app/apps/api/content/urls.py
from django.urls import path
from .views import ContentListAPIView

# URL for displaying feedpost current user
urlpatterns = [
	path('', ContentListAPIView.as_view()),
]

app/apps/content/urls.py
from django.urls import path
from .views import ContentView

app_name = 'content'

urlpatterns = [
	path('', ContentView.as_view(), name='content')
]

app/apps/tools/urls.py
from django.urls import path
from .views import *

app_name = 'tools'

urlpatterns = [
	path('like/', post_like, name='post_like'),
	path('comment/', post_comment, name='post_comment'),
	path('follow/', follow_profile, name='follow_profile'),
	path('upload_photo/', upload_photo, name='upload_photo'),
	path('upload_avatar/', upload_avatar, name='upload_avatar'),
	path('delete_photo/', delete_photo, name='delete_photo')
]

app/apps/userpost/urls.py
from django.urls import path
from .views import PhotoView

app_name = 'userpost'

urlpatterns = [
	path('', PhotoView.as_view(), name='userpost')
]

app/apps/userprofile/urls.py
from django.urls import path
from .views import ProfileView, FollowersView, UserLogoutView

app_name = 'userprofile'

urlpatterns = [
	path('logout/', UserLogoutView.as_view(), name='logout'),
	path('followers/', FollowersView.as_view(), name='followers'),
	path('following/', FollowersView.as_view(), name='following'),
	path('', ProfileView.as_view(), name='userprofile'),
]	

app/instclone/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
	path('', include('main.urls')),
	path('content/', include('content.urls')),
	path('admin/', admin.site.urls),
	path('notifications/', include('notifications.urls')),
    path('explore/', include('explore.urls')),
	path('p/<int:pk>/', include('userpost.urls')),
    path('tools/', include('tools.urls')),
    path('api/v1/', include('api.urls')),
	path('<str:username>/', include('userprofile.urls')),
]

if settings.DEBUG:
    import debug_toolbar	

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/apps/content/models.py
from django.db import models

# Create your models here.

app/apps/api/content/views.py
from rest_framework.generics import ListAPIView
from comment.models import Comment
from .serializers import ContentModelSerializer
from .paginations import StandardResultsSetPagination
from userpost.models import UserPost
from django.db.models import Prefetch, OuterRef, Exists, Count
from like.models import PostLike


class ContentListAPIView(ListAPIView):
	"""
	API view for listing content in the feed.

	"""

	serializer_class = ContentModelSerializer
	pagination_class = StandardResultsSetPagination

	def get_queryset(self):
		"""
		Get the queryset of content with related user data, comments, and like counts.

		"""
		user = self.request.user
		likes_subquery = PostLike.objects.filter(post=OuterRef('pk'), user=user)

		return UserPost.objects.select_related('user').only('user__username', 'user__avatar', 'image', 'caption', 'timestamp').prefetch_related(
			Prefetch('comments', queryset=Comment.objects.select_related('user').only('user__username', 'post', 'text'))
		).annotate(
			current_user_liked=Exists(likes_subquery),
			likes_count=Count('likes')
		)

app/apps/content/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .content_services import extended_information, get_filtered_photos


class ContentView(ListView):
	"""
	Class for displaying the feed of posts for the current user.
	
	"""
	context_object_name = 'photos'
	template_name = 'content/content.html'

	def get_queryset(self):
		# Retrieve and return the queryset for the posts
		return get_filtered_photos(self)
	
	def get_context_data(self, **kwargs):
		# Get additional information and add it to the context
		context = super().get_context_data(**kwargs)
		return extended_information(self, context, **kwargs)

app/apps/content/templates/content/content.html
{% extends 'base.html' %}
{% block content %}
{% load custom_filters %}
{% load static %}

{% for photo in photos %}
<div class="card">
	<a href="{% url 'userprofile:userprofile' photo.custom_user.username %}" class="card_header">
		<div class="card_header_avatar">
			{% if photo.custom_user.avatar %}
				<img src="{{ photo.custom_user.get_url }}" alt="">
			{% else %}
				<img src="{% static 'main/images/default.jpg' %}" alt="">
			{% endif %}
		</div>
		<div class="card_user">{{ photo.custom_user.username|lower }}</div>
		<div class="card_post_date">• {{ photo.timestamp|time_since }}</div>
	</a>
	<a href="{% url 'userpost:userpost' photo.pk %}">
		<div class="content_image" tabindex="0">
		<img class="photo" src="{{ photo.get_url }}" alt="">
		</div>
	</a>
	<div class="card__content">
		<div class="interaction__panel">
			<button class="like-button panel_button" data-photo-id="{{ photo.id }}">
				<i class="fa-solid fa-heart {% if photo.id in liked_photo_ids %}liked{% endif %}"></i>
			</button>
			<button class="panel_button">
				<a href="{% url 'userpost:userpost' photo.pk %}"><i class="fa-regular fa-comment"></i></a>
			</button>
			<button class="panel_button"><i class="fa-regular fa-paper-plane"></i></button>
			<button class="panel_button last-btn"><i class="fa-regular fa-floppy-disk"></i></button>
		</div>
		<strong>{{ photo.likes_count }} likes</strong>
		<div class="card__title">
			{% if photo.caption %}
				<a href="{% url 'userprofile:userprofile' photo.custom_user.username %}">
					<strong>{{ photo.custom_user.username }}</strong>
				</a>
				{{ photo.caption }}</div>
			{% endif %}
		<div class="card__desc">
			<div class="comments">
				{% for comment in photo.first_two_comments %}
					<div class="comment">
						<a href="{% url 'userprofile:userprofile' comment.custom_user.username %}" class="username-link">
							<strong class="username">{{ comment.custom_user.username|lower }}</strong>
						</a>
						<p class="comment-text">{{ comment.text }}</p>
					</div>
				{% endfor %}
			</div>
		</div>
		<form action="{% url 'tools:post_comment' %}" method="post">
			<div class="comment_container">
			{% csrf_token %}
			<input type="hidden" name="form_type" value="comment_form">
			<input type="hidden" name="id" value="{{ photo.pk }}">
			<input type="text" name="text" class="comment__area" placeholder="Add a comment..." value="{{ form.text.value|default:'' }}" required>
			<button type="submit" class="card__send__comment" name="comment-btn">Send</button>
		</div>
		</form>
	</div>
</div>
{% endfor %}
{% endblock %}