app/apps/explore/urls.py
from django.urls import path
from .views import ExploreListView


app_name = 'explore'

urlpatterns = [
	path('', ExploreListView.as_view(), name='explore')
]

app/apps/notifications/urls.py
from django.conf import settings
from django.urls import include, path
from .views import NotificationsView, get_unread_notifications_count, mark_notifications_read
from django.conf.urls.static import static

app_name = 'notifications'


urlpatterns = [
	path('unread-count/', get_unread_notifications_count, name='unread_notifications_count'),
	path('mark-read/', mark_notifications_read, name='mark_notifications_read'),
	path('', NotificationsView.as_view(), name='notifications')
]

app/apps/tools/urls.py
from django.urls import path
from .views import *

app_name = 'tools'

urlpatterns = [
	path('like/', post_like, name='post_like'),
	path('comment/', post_comment, name='post_comment'),
	path('follow/', follow_profile, name='follow_profile'),
	path('upload_photo/', upload_photo, name='upload_photo'),
	path('upload_avatar/', upload_avatar, name='upload_avatar'),
	path('delete_photo/', delete_photo, name='delete_photo')
]

app/apps/userprofile/urls.py
from django.urls import path
from .views import ProfileView, FollowersView, UserLogoutView

app_name = 'userprofile'

urlpatterns = [
	path('logout/', UserLogoutView.as_view(), name='logout'),
	path('followers/', FollowersView.as_view(), name='followers'),
	path('following/', FollowersView.as_view(), name='following'),
	path('', ProfileView.as_view(), name='userprofile'),
]	

app/instclone/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
	path('', include('main.urls')),
	path('content/', include('content.urls')),
	path('admin/', admin.site.urls),
	path('notifications/', include('notifications.urls')),
    path('explore/', include('explore.urls')),
	path('p/<int:pk>/', include('userpost.urls')),
    path('tools/', include('tools.urls')),
    path('api/v1/', include('api.urls')),
	path('<str:username>/', include('userprofile.urls')),
]

if settings.DEBUG:
    import debug_toolbar	

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	{% block title %}{% endblock %}
	<link type="text/css" rel="stylesheet" href="{% static 'main/css/main.css' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
 <div class="grid">
	<div class="sidebar">
		<a href="/">
			<img src="{% static 'main/images/piclink.png' %}" alt="Логотип" width="120px">
		</a>
		<nav class="sidebar-nav">
			<ul>
				<a href="/"><li><i class="fas fa-home"></i>Home</li></a>
				<a href="{% url 'explore:explore' %}"><li><i class="fa-regular fa-compass"></i> Explore</li></a>
				{% if user.is_authenticated %}
				<a href="{% url 'notifications:notifications' %}"><li><i class="fa-regular fa-heart"></i> Notification <span id="notificationCounter"></span></li></a>
				<li id="openModal" class="custom-button"><i class="fa-solid fa-plus"></i> Create</li>
				<div id="myModal" class="modal">
					<div class="modal-content">
							<span class="close">&times;</span>
							<form method="post" class="header-upload-form" enctype="multipart/form-data" action="{% url 'tools:upload_photo' %}">
									{% csrf_token %}
									<h2>Create new post</h2>
									<label class="custom-upload-btn">
										<input class="upload-photo-btn" type="file" name="file" required onchange="showSelectedPhoto(event)">
										Upload Photo
									</label>	
								
								<button id="uploadButton" style="display: none;" name="upload-photo" type="submit">Upload</button>
								
								<button id="confirmButton" class="confirm-upload-btn" style="display: none;" type="button" onclick="confirmUpload()">Confirm</button>
								
								<div id="selectedPhotoContainer" class="selector-photo" style="display: none;">
										<img class="selected-photo" id="selectedPhoto" src="" alt="Selected Photo">
								</div>
							</form>
					</div>
				</div>
				<a href="{% url 'userprofile:userprofile' request.user.username %}"><li><i class="fa-regular fa-user"></i> Profile</li></a>
				{% endif %}
			</ul>
		</nav>
	</div>
	<div class="content">
		{% block scripts %} {% endblock %}
		{% block content %} {% endblock %}
	</div>
	<div class="footer">{{ debug }}</div>
 </div>	

	
</body>
<script src="{% static 'main/js/main.js' %}" defer></script>
<script src="{% static 'notifications/js/notifications.js' %}" defer></script>
</html>